ALTER TABLE "Season" ADD COLUMN IF NOT EXISTS "simulationState" TEXT NOT NULL DEFAULT 'READY';
ALTER TABLE "Season" ADD COLUMN IF NOT EXISTS "virtualNowMs" BIGINT NOT NULL DEFAULT 0;
ALTER TABLE "Season" ADD COLUMN IF NOT EXISTS "resumedAt" TIMESTAMP(3);
ALTER TABLE "Season" ADD COLUMN IF NOT EXISTS "pausedAt" TIMESTAMP(3);
ALTER TABLE "Season" ADD COLUMN IF NOT EXISTS "finishedAt" TIMESTAMP(3);
UPDATE "Season" SET "simulationState" = CASE WHEN "status" = 'FINISHED' THEN 'FINISHED' ELSE 'READY' END WHERE "simulationState" = 'READY';
