import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';
import { Logo } from './Logo';
import { CircleDot, Flag, Square, ShieldCheck, Activity } from 'lucide-react';
import { countdown as clockCountdown } from './clock';

type Status = 'UPCOMING' | 'LIVE' | 'FINISHED';
type Team = { id: string; name: string; initials: string; base_rating: number; logoUrl?: string | null };
type Market = { key: string; group: string; name: string; line?: number; status: string; outcomes: { selection: string; label: string; odds: number; fairProbability: number }[] };
type TimelineEvent = { id: string; minute: number; type: string; side: 'home' | 'away'; subject?: string; confirmed?: boolean };
const eventLabel: Record<string, string> = { GOAL: 'Гол', SHOT: 'Удар', CORNER: 'Угловой', FOUL: 'Фол', FREE_KICK: 'Штрафной', OFFSIDE: 'Офсайд', YELLOW_CARD: 'Жёлтая карточка', RED_CARD: 'Красная карточка', INJURY: 'Травма', PENALTY: 'Пенальти', VAR_CHECK: 'VAR CHECK', VAR_DECISION: 'VAR DECISION' };
function EventIcon({type}: {type: string}) { const Icon = type.startsWith('VAR') ? ShieldCheck : type.includes('CARD') ? Square : type === 'GOAL' ? CircleDot : type === 'CORNER' ? Flag : Activity; return <Icon size={16} aria-hidden />; }
function Timeline({event, compact = false}: {event: Event; compact?: boolean}) { const rows = compact ? event.timeline.slice(-2) : [...event.timeline].reverse(); return <div className="timeline">{!compact && <h2>MATCH TIMELINE</h2>}{rows.map(e => <div className="timeline-row" key={e.id}><b>{e.minute}′</b><EventIcon type={e.type}/><span>{eventLabel[e.type]}{e.subject && ` · ${eventLabel[e.subject]}`}{e.type === 'VAR_DECISION' && (e.confirmed ? ' · подтверждено' : ' · отменено')}<small>{e.side === 'home' ? event.home_team.name : event.away_team.name}</small></span></div>)}</div>; }
function Crest({team}: {team: Team}) { return team.logoUrl ? <img className="mini-crest" src={team.logoUrl} alt={team.name}/> : <span className="mini-crest p">{team.initials}</span>; }
type Event = { minute: number | null; score: { home: number; away: number } | null; timeline: TimelineEvent[]; market_status: 'OPEN' | 'SUSPENDED' | 'CLOSED'; fixture_id: string; season_id: string; competition_id: string; league: string; round: number; home_team: Team; away_team: Team; kickoff_at: string; finish_at: string; duration_seconds: number; status: Status; final_score: { home: number; away: number } | null; markets: Market[]; available_markets: number; server_now: string };
type Season = { season_id: string; season_number: number; started_at: string; ends_at: string; server_now: string; status: string; seed_commit: string };
type EventResponse = { server_now: string; season: Season; competitions: { id: string; name: string }[]; counts: { upcoming: number; live: number }; filters: { total: number; pages: number; page: number }; events: Event[] };
const ruTime = (iso: string) => new Date(iso).toLocaleTimeString('ru-RU', { hour: '2-digit', minute: '2-digit' });
const ruDateTime = (iso: string) => new Date(iso).toLocaleString('ru-RU', { day: '2-digit', month: '2-digit', hour: '2-digit', minute: '2-digit' });
const statusLabel: Record<Status, string> = { UPCOMING: 'Предстоящий', LIVE: 'LIVE', FINISHED: 'Завершён' };
async function jsonOk<T>(response: Response): Promise<T> { if (!response.ok) throw new Error(`API недоступен (${response.status})`); return response.json() as Promise<T>; }

function useServerClock(serverNow?: string, onResync?: () => void) {
  const offset = serverNow ? Date.parse(serverNow) - Date.now() : 0;
  const [now, setNow] = useState(() => Date.now() + offset);
  useEffect(() => { setNow(Date.now() + offset); const timer = window.setInterval(() => setNow(Date.now() + offset), 1000); return () => window.clearInterval(timer); }, [offset]);
  useEffect(() => { const onVisible = () => { if (document.visibilityState === 'visible') onResync?.(); }; document.addEventListener('visibilitychange', onVisible); return () => document.removeEventListener('visibilitychange', onVisible); }, [onResync]);
  return now;
}
function countdown(target: string, now: number) { return clockCountdown(target, now, 0); }
function navigate(path: string) { window.history.pushState({}, '', path); window.dispatchEvent(new PopStateEvent('popstate')); }

function App() {
  const [route, setRoute] = useState(window.location.pathname);
  const [season, setSeason] = useState<Season>();
  const [serverNow, setServerNow] = useState<string>();
  const [error, setError] = useState('');
  const syncSeason = useCallback(async () => { try { const res = await fetch('/api/season'); if (!res.ok) throw new Error('Не удалось синхронизировать сезон'); const value = await res.json() as Season; setSeason(value); setServerNow(value.server_now); } catch (e) { setError(e instanceof Error ? e.message : 'Ошибка соединения'); } }, []);
  useEffect(() => { const onRoute = () => setRoute(window.location.pathname); window.addEventListener('popstate', onRoute); let poll: number | undefined; (async () => { try { await jsonOk(await fetch('/api/session', { method: 'POST' })); await syncSeason(); poll = window.setInterval(syncSeason, 60_000); } catch (e) { setError(e instanceof Error ? e.message : 'База данных временно недоступна'); } })(); return () => { window.removeEventListener('popstate', onRoute); if (poll) window.clearInterval(poll); }; }, [syncSeason]);
  const now = useServerClock(serverNow, syncSeason);
  const detailId = route.match(/^\/matches\/([^/]+)/)?.[1];
  return <div className="shell"><Sidebar route={route} /><main className="main"><Topbar season={season} now={now} /><div className="page-error">{error}</div>{detailId ? <DetailPage fixtureId={detailId} season={season} now={now} onBack={() => navigate('/matches')} /> : route === '/matches' ? <MatchesPage season={season} now={now} /> : <HomePage season={season} now={now} />}</main><Slip /></div>;
}
function Sidebar({ route }: { route: string }) { return <aside className="sidebar"><button className="brand" onClick={() => navigate('/')}><Logo /></button><div className="season-card"><div className="eyebrow">ПЕРСОНАЛЬНАЯ ВСЕЛЕННАЯ</div><strong>Только виртуальный футбол</strong><div className="season-progress"><i /></div><div className="tiny">40 клубов · 4 лиги · 100 матчей</div></div><nav><button className={'nav ' + (route === '/' ? 'active' : '')} onClick={() => navigate('/')}><span>◈</span>Обзор</button><button className={'nav ' + (route.startsWith('/matches') ? 'active' : '')} onClick={() => navigate('/matches')}><span>⌁</span>Линия матчей</button></nav><div className="sidebar-foot"><div className="status-dot"><i /> СИМУЛЯЦИЯ ОНЛАЙН</div><div className="tiny">Только вымышленные события<br />UPX не имеет денежной стоимости</div></div></aside>; }
function Topbar({ season, now }: { season?: Season; now: number }) { return <header className="topbar"><div className="mobile-brand">1UPX <span>/ VIRTUAL</span></div><div className="season-top"><span>SEASON #{String(season?.season_number ?? 1).padStart(2, '0')}</span><b>До конца сезона: {season ? countdown(season.ends_at, now) : '—'}</b></div><div className="top-actions"><div className="avatar">UP</div></div></header>; }
function SeasonStrip({ season, now, counts }: { season?: Season; now: number; counts?: { upcoming: number; live: number } }) { return <div className="season-strip"><div><span className="kicker">SEASON #{String(season?.season_number ?? 1).padStart(2, '0')}</span><strong>До конца сезона: {season ? countdown(season.ends_at, now) : '—'}</strong></div><div className="strip-stats"><span><b>{counts?.upcoming ?? '—'}</b> предстоящих</span><span><b>{counts?.live ?? 0}</b> LIVE</span></div></div>; }
function HomePage({ season, now }: { season?: Season; now: number }) { const [data, setData] = useState<EventResponse>(); useEffect(() => { const load = () => fetch('/api/virtual/events?page_size=5').then(jsonOk<EventResponse>).then(setData).catch(() => setData(undefined)); load(); const timer = window.setInterval(load, 5_000); return () => window.clearInterval(timer); }, [season?.season_id]); return <section><div className="page-heading"><div><div className="kicker">ВИРТУАЛЬНЫЙ ДЕНЬ · SERVER-SYNCED</div><h1>Обзор сезона</h1><p>Вымышленные футбольные события, созданные только для вашей вселенной.</p></div><div className="live-pill"><i /> POSTGRESQL · ONLINE</div></div><SeasonStrip season={season} now={now} counts={data?.counts} /><div className="section-row"><div className="section-title"><span>Ближайшие события</span><small>Подтверждено сервером</small></div><button className="primary compact" onClick={() => navigate('/matches')}>Смотреть все матчи <span>↗</span></button></div><div className="matches home-matches">{data?.events.map((event, i) => <EventCard event={event} now={now} key={event.fixture_id} compact={i > 2} />)}</div>{!data && <div className="loading-card">Загружаем расписание вашего сезона…</div>}</section>; }
function MatchesPage({ season, now }: { season?: Season; now: number }) { const [status, setStatus] = useState('ALL'); const [competition, setCompetition] = useState('ALL'); const [page, setPage] = useState(1); const [data, setData] = useState<EventResponse>(); const load = useCallback(() => { const params = new URLSearchParams({ page: String(page), page_size: '20' }); if (status !== 'ALL') params.set('status', status); if (competition !== 'ALL') params.set('competition', competition); fetch('/api/virtual/events?' + params).then(jsonOk<EventResponse>).then(setData).catch(() => setData(undefined)); }, [page, status, competition]); useEffect(() => { load(); const timer = window.setInterval(load, 5_000); return () => window.clearInterval(timer); }, [load, season?.season_id]); const leagues = useMemo(() => data?.competitions ?? [], [data]); return <section><div className="page-heading"><div><div className="kicker">SEASON #{String(season?.season_number ?? 1).padStart(2, '0')} · ЛИНИЯ</div><h1>Линия матчей</h1><p>100 матчей текущего персонального сезона. Состояния определяются серверным временем.</p></div><div className="live-pill"><i /> LIVE-СИМУЛЯЦИЯ</div></div><SeasonStrip season={season} now={now} counts={data?.counts} /><div className="filters-panel"><div className="filters">{[['ALL', 'Все'], ['LIVE', 'LIVE'], ['UPCOMING', 'Предстоящие'], ['FINISHED', 'Завершённые']].map(([key, label]) => <button key={key} className={'filter ' + (status === key ? 'active' : '')} onClick={() => { setStatus(key); setPage(1); }}>{label}</button>)}</div><div className="league-filters"><button className={'filter ' + (competition === 'ALL' ? 'active' : '')} onClick={() => { setCompetition('ALL'); setPage(1); }}>Все лиги</button>{leagues.map(league => <button key={league.id} className={'filter ' + (competition === league.id ? 'active' : '')} onClick={() => { setCompetition(league.id); setPage(1); }}>{league.name}</button>)}</div></div><div className="line-meta"><span>{data?.filters.total ?? '—'} событий · страница {data?.filters.page ?? page}</span><span>LIVE первыми · upcoming по старту</span></div><div className="matches">{data?.events.map(event => <EventCard key={event.fixture_id} event={event} now={now} />)}</div>{data && data.filters.pages > 1 && <div className="pagination"><button className="filter" disabled={page <= 1} onClick={() => setPage(p => p - 1)}>← Назад</button><span>{page} / {data.filters.pages}</span><button className="filter" disabled={page >= data.filters.pages} onClick={() => setPage(p => p + 1)}>Дальше →</button></div>}</section>; }
function EventCard({ event, now, compact = false }: { event: Event; now: number; compact?: boolean }) { const market = event.markets.find(m => m.group === '1X2'); return <article className={'match-card event-card ' + (compact ? 'event-compact' : '')} onClick={() => navigate('/matches/' + event.fixture_id)}><div className="event-top"><span className={'state state-' + event.status.toLowerCase()}>{event.status === 'LIVE' && <i />}{statusLabel[event.status]}{event.status === 'LIVE' && ` ${event.minute ?? 0}′`}{event.market_status === 'SUSPENDED' && ' · VAR CHECK'}</span><span className="match-meta">{event.league} · ТУР {event.round}</span></div><div className="event-body"><div className="event-team"><Crest team={event.home_team} /><strong>{event.home_team.name}</strong></div><div className="event-center">{(event.final_score ?? event.score) ? <b className="score">{(event.final_score ?? event.score)!.home} : {(event.final_score ?? event.score)!.away}</b> : event.status === 'UPCOMING' ? <><b>{ruTime(event.kickoff_at)}</b><small>через {countdown(event.kickoff_at, now)}</small></> : <><b className="live-text">LIVE</b><small>рынки закрыты</small></>}</div><div className="event-team away"><Crest team={event.away_team} /><strong>{event.away_team.name}</strong></div></div><Timeline event={event} compact /><div className="event-foot"><span>{event.status === 'UPCOMING' ? 'Начало ' + ruDateTime(event.kickoff_at) : event.status === 'FINISHED' ? 'Матч завершён · счёт зафиксирован' : 'Событие идёт · серверное состояние LIVE'}</span><div className="mini-odds">{market ? market.outcomes.map(o => <span className="mini-odd" key={o.selection}>{o.label} <b>{o.odds.toFixed(2)}</b></span>) : <span className="market-closed">{event.status === 'FINISHED' ? 'Коэффициенты закрыты' : 'Рынки недоступны'}</span>}<span className="market-count">{event.available_markets} markets ↗</span></div></div></article>; }
function DetailPage({ fixtureId, season, now, onBack }: { fixtureId: string; season?: Season; now: number; onBack: () => void }) { const [data, setData] = useState<{ event: Event; server_now: string; ratings: unknown }>(); useEffect(() => { const load = () => fetch('/api/virtual/events/' + fixtureId).then(jsonOk<{ event: Event; server_now: string; ratings: unknown }>).then(setData).catch(() => undefined); load(); const timer = window.setInterval(load, 3000); return () => window.clearInterval(timer); }, [fixtureId]); const event = data?.event; return <section><button className="back-link" onClick={onBack}>← Вернуться в линию</button>{!event ? <div className="loading-card">Загружаем матч…</div> : <><div className="detail-heading"><div><div className="kicker">{event.league} · ТУР {event.round} · SEASON #{String(season?.season_number ?? 1).padStart(2, '0')}</div><h1>{event.home_team.name} <span>vs</span> {event.away_team.name}</h1><p>{ruDateTime(event.kickoff_at)} · {statusLabel[event.status]} · server_now {ruTime(data.server_now)}</p></div><div className={'state state-' + event.status.toLowerCase()}>{event.status === 'LIVE' && <i />}{statusLabel[event.status]}</div></div><div className="detail-score-card"><div className="detail-team"><div className="crest crest-purple">{event.home_team.initials}</div><strong>{event.home_team.name}</strong><small>Рейтинг {event.home_team.base_rating}</small></div><div className="detail-score">{(event.final_score ?? event.score) ? <b>{(event.final_score ?? event.score)!.home} : {(event.final_score ?? event.score)!.away}</b> : <b>— : —</b>}<small>{event.status === 'UPCOMING' ? 'до начала ' + countdown(event.kickoff_at, now) : event.status === 'LIVE' ? `LIVE ${event.minute}′ · ${event.market_status}` : 'итог зафиксирован'}</small></div><div className="detail-team"><div className="crest crest-orange">{event.away_team.initials}</div><strong>{event.away_team.name}</strong><small>Рейтинг {event.away_team.base_rating}</small></div></div><Timeline event={event}/><div className="detail-section"><div className="section-title"><span>Рынки матча</span><small>{event.status === 'UPCOMING' ? 'prematch · Football Odds Engine' : `LIVE · ${event.market_status}`}</small></div>{event.markets.length ? <div className="markets-grid">{event.markets.map(m => <div className="market-panel" key={m.key}><div><strong>{m.name}</strong>{m.line !== undefined && <small>Линия {m.line}</small>}</div><div className="market-outcomes">{m.outcomes.map(o => <button className="market-outcome" key={o.selection} disabled title="Размещение ставок появится в Phase 6"><span>{o.label}</span><b>{o.odds.toFixed(2)}</b></button>)}</div></div>)}</div> : <div className="closed-panel">{event.status === 'LIVE' ? 'LIVE repricing не реализован: prematch коэффициенты не показываются как LIVE.' : 'Матч завершён. Коэффициенты закрыты.'}</div>}</div></>}</section>; }
function Slip() { return <aside className="slip"><div className="slip-head"><div><div className="kicker">PHASE 6</div><h2>Купон</h2></div></div><div className="empty-slip"><div className="empty-icon">⌁</div><strong>Ставки ещё не подключены</strong><p>Выбор исходов станет доступен после проверенного betting backend.</p></div><div className="slip-bottom"><p className="slip-note">Сейчас доступны только просмотр линии и prematch markets. UPX не имеет денежной стоимости.</p></div></aside>; }
createRoot(document.getElementById('root')!).render(<App />);
